export const GET_STRATEGIES_CREATED_TABLE_DATA =
  "GET_STRATEGIES_CREATED_TABLE_DATA";
export const GET_TOTAL_USER_CREATED_STRATEGY_COUNT =
  "GET_TOTAL_USER_CREATED_STRATEGY_COUNT";
export const GET_REFERRAL_CODES_MODULUS = "GET_REFERRAL_CODES_MODULUS";
export const GET_USER_PROFILE_DATA = "GET_USER_PROFILE_DATA";
